name: Build Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

permissions:
  contents: read

jobs:
  build-rdkssa:
    name: Build rdkssa component in GitHub rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install native build dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends libsafec-dev
          test -f /usr/include/safec/safec_lib.h

      - name: native build
        run: |
          chmod +x cov_build.sh
          ./cov_build.sh
